function init(self)
	msg.post("#inner_proxy", "load")
end

function final(self)
end

function update(self, dt)
end

function fixed_update(self, dt)
end

local MSG_PROXY_LOADED = hash("proxy_loaded")

function on_message(self, message_id, message, sender)
	if message_id == MSG_PROXY_LOADED then
		msg.post(sender, "enable")
		msg.post(sender, "acquire_input_focus")
	end
end

function on_input(self, action_id, action)
end

function on_reload(self)
end
